defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

[providers.docker]
  # swarm classic (1.12-)
  #endpoint = "tcp://127.0.0.1:2377"
  endpoint = "unix:///var/run/docker.sock"
  swarmMode = true